### ISSUE TITLE
Error detected while processing foobar/javascript.vim

### ISSUE THREAD

**Issue by drodrigo** [pangloss/vim-javascript#413]
Hello,

I updated my plugins today and this error is thrown:

E59: invalid character after \@
E475: Invalid argument: jsRegexpString     start=+\%(\%(\%(return\|case\)\s\+\)\@50<=\|\%(\%([)\]"']\|\d\|\w\)\s*\)\@50<!\)/\(\*\|/\)\@!+ skip=+\\.\|\[\%(\\.\|[^]]\)*\]+ end=+/[gimy]\{,4}+ contains=
jsRegexpCharClass,jsRegexpGroup,@jsRegexpSpecial,@htmlPreproc oneline keepend

I can't really tell what this error means, maybe it's due a recent change?

Thanks.

**Comment by amadeus** [comment]
This is because you are using an older version of vim and we recently pushed out a change. I am about to merge something into the `develop` branch that will fix this.

**Comment by amadeus** [comment]
If you checkout the `develop` branch, this should be fixed.

**Comment by drodrigo** [comment]
Thanks, it works now!

**Comment by tjwebb** [comment]
Also ran into this. I think OSX includes vim 7.3. I upgraded to 7.4 and the problem went away.

**Comment by yanyiwu** [comment]
@tjwebb Thanks, it works!

**Comment by GeneDockAkira** [comment]
@tjwebb Hi, Travis, I upgrade vim to 7.4 (use brew), but the problem is still there. Is that my vim version is wrong? thx.
![image](https://cloud.githubusercontent.com/assets/17537378/15415738/60aa075c-1e77-11e6-8cea-414d98968705.png)
